---
{{- if .Values.global.createClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "druid-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: druid-operator
    app.kubernetes.io/part-of: druid-operator
  name: {{ include "druid-operator.fullname" . }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "druid-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: druid-operator
    app.kubernetes.io/part-of: druid-operator
  name: {{ include "druid-operator.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "druid-operator.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "druid-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
