---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - druid.apache.org
  resources:
  - druids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - druid.apache.org
  resources:
  - druids/status
  verbs:
  - get
  - patch
  - update
