apiVersion: druid.apache.org/v1alpha1
kind: DruidIngestion
metadata:
  labels:
    app.kubernetes.io/name: druidingestion
    app.kubernetes.io/instance: druidingestion-sample
  name: kafka-1
spec:
  suspend: false
  druidCluster: tiny-cluster
  ingestion:
    type: kafka
    spec: |-
      {
        "type": "kafka",
        "spec": {
          "dataSchema": {
            "dataSource": "metrics-kafka",
            "timestampSpec": {
              "column": "timestamp",
              "format": "auto"
            },
            "dimensionsSpec": {
              "dimensions": [],
              "dimensionExclusions": [
                "timestamp",
                "value"
              ]
            },
            "metricsSpec": [
              {
                "name": "count",
                "type": "count"
              },
              {
                "name": "value_sum",
                "fieldName": "value",
                "type": "doubleSum"
              },
              {
                "name": "value_min",
                "fieldName": "value",
                "type": "doubleMin"
              },
              {
                "name": "value_max",
                "fieldName": "value",
                "type": "doubleMax"
              }
            ],
            "granularitySpec": {
              "type": "uniform",
              "segmentGranularity": "HOUR",
              "queryGranularity": "NONE"
            }
          },
          "ioConfig": {
            "topic": "metrics",
            "inputFormat": {
              "type": "json"
            },
            "consumerProperties": {
              "bootstrap.servers": "localhost:9092"
            },
            "taskCount": 1,
            "replicas": 1,
            "taskDuration": "PT1H"
          },
          "tuningConfig": {
            "type": "kafka",
            "maxRowsPerSegment": 5000000
          }
        }
      }
